
ALTER DATABASE BankDB SET RECOVERY FULL;


BACKUP DATABASE BankDB
TO DISK = 'D:\SQLData\Backup\BankDB_FULL_COMPRESSED.bak'
WITH INIT, COMPRESSION;


BACKUP DATABASE BankDB
TO DISK= 'D:\SQLData\Backup\BankDB_DIFF.bak'
WITH DIFFERENTIAL, COMPRESSION;

BACKUP DATABASE BankDB
TO DISK= 'D:\SQLData\Backup\BankDB_DIFF1.bak'
WITH DIFFERENTIAL, COMPRESSION;

BACKUP LOG BankDB
TO DISK= 'D:\SQLData\Backup\BankDB_Log.trn'
WITH INIT;








