RESTORE MASTER KEY
FROM FILE = 'D:\SQLData\Securities\master_key.bak'
DECRYPTION BY PASSWORD = 'pass2'
ENCRYPTION BY PASSWORD = 'pass3'; 


OPEN MASTER KEY DECRYPTION BY PASSWORD = 'pass3';

CREATE CERTIFICATE BackupCert
FROM FILE = 'D:\SQLData\Securities\BackupCert.cer'
WITH PRIVATE KEY (
    FILE = 'D:\SQLData\Securities\BackupCert.pvk',
    DECRYPTION BY PASSWORD = 'pass3'
);
GO


ALTER DATABASE BankDB
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE BankDB
FROM DISK = 'D:\SQLData\Backup\BankDB_Encrypted_FULL.bak'
with REPLACE;

ALTER DATABASE BankDB
SET MULTI_USER;
GO
