BACKUP DATABASE CARD_DB
TO DISK= 'D:\SQLData\Backup\CARD_FULL_COMPRESSED.bak'
WITH INIT;

BACKUP DATABASE CARD_DB
TO DISK= 'D:\SQLData\Backup\CARD_DIFF.bak'
WITH DIFFERENTIAL, INIT;

BACKUP DATABASE CARD_DB
TO DISK= 'D:\SQLData\Backup\CARD_DIFF1.bak'
WITH DIFFERENTIAL, INIT;

BACKUP LOG CARD_DB
TO DISK= 'D:\SQLData\Backup\CARD_Log.trn'
WITH INIT;



