ALTER DATABASE OrderDB ADD FILEGROUP FG_2011;
ALTER DATABASE OrderDB ADD FILEGROUP FG_2012;
ALTER DATABASE OrderDB ADD FILEGROUP FG_2013;
ALTER DATABASE OrderDB ADD FILEGROUP FG_2014;
ALTER DATABASE OrderDB ADD FILEGROUP FG_2015_PLUS;


ALTER DATABASE OrderDB ADD FILE (
    NAME = Sales2011,
    FILENAME = 'D:\SQLData\SalesOrder2011.ndf',
    SIZE = 500MB,
    FILEGROWTH = 100MB
) TO FILEGROUP FG_2011;

ALTER DATABASE OrderDB ADD FILE (
    NAME = Sales2012,
    FILENAME = 'D:\SQLData\SalesOrder2012.ndf',
    SIZE = 500MB,
    FILEGROWTH = 100MB
) TO FILEGROUP FG_2012;

ALTER DATABASE OrderDB ADD FILE (
    NAME = Sales2013,
    FILENAME = 'D:\SQLData\SalesOrder2013.ndf',
    SIZE = 1GB,
    FILEGROWTH = 200MB
) TO FILEGROUP FG_2013;

ALTER DATABASE OrderDB ADD FILE (
    NAME = Sales2014,
    FILENAME = 'D:\SQLData\SalesOrder2014.ndf',
    SIZE = 1GB,
    FILEGROWTH = 200MB
) TO FILEGROUP FG_2014;

ALTER DATABASE OrderDB ADD FILE (
    NAME = Sales2015Plus,
    FILENAME = 'D:\SQLData\SalesOrder2015Plus.ndf',
    SIZE = 1GB,
    FILEGROWTH = 200MB
) TO FILEGROUP FG_2015_PLUS;



CREATE PARTITION FUNCTION PF_OrderDate (DATE)
AS RANGE RIGHT FOR VALUES
(
    '2012-01-01',
    '2013-01-01',
    '2014-01-01',
    '2015-01-01'
);


ALTER TABLE SalesOrderDetail
ALTER COLUMN ModifiedDate DATE;





SELECT name
FROM sys.filegroups;

CREATE PARTITION SCHEME PS_OrderDate
AS PARTITION PF_OrderDate
TO (
    FG_2011,
    FG_2012,
    FG_2013,
    FG_2014,
    FG_2015_PLUS
);



CREATE CLUSTERED INDEX CX_SalesOrderDetail_ModifiedDate
ON SalesOrderDetail (ModifiedDate, SalesOrderID)
ON PS_OrderDate (ModifiedDate);

